# Site settings
title: Jun Zhou's Portfolio
email: jzhou3087@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Computer Science. Engineer. Data Science. Data Structures and Algorithms. Internet Architecture. Music Enthusiast. Writer. Rhetoric.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jzhou3087.github.io" # the base hostname & protocol for your site
github_username:  jzhou3087

# Build settings
markdown: kramdown
permalink: none
